[build]
  base = "/"
  publish = "public/"  # Folder yang akan di-deploy

[[plugins]]
  package = "@netlify/plugin-functions-core"

# Konfigurasi serverless functions
[functions]
  # Definisi serverless function pertama
  [[functions]]
  path = "/api/*"  # Semua endpoint API
  command = "node server.js"  # Perintah untuk menjalankan server.js
